use crate::{db::schemas::worte::NewWorteSchema as New, test_utils::scenarios::Scenario};

pub fn scenario_worte() -> Scenario<New> {
    Scenario {
        initial: vec![
            New {
                gram_type: vec![12, 27],
                gender_id: None,
                worte_de: "weitergehen".into(),
                worte_es: "seguir".into(),
                plural: None,
                niveau_id: 1,
                example_de: "Wir gehen weiter, bis wir zu Hause sind.".into(),
                example_es: "Seguimos hasta llegar a casa.".into(),
                verb_aux: Some("sein".into()),
                trennbar: Some(true),
                reflexiv: Some(false),
            },
            New {
                gram_type: vec![9, 31],
                gender_id: None,
                worte_de: "müde werden".into(),
                worte_es: "ponerse cansado".into(),
                plural: None,
                niveau_id: 1,
                example_de: "Ich werde nach der Arbeit immer müde.".into(),
                example_es: "Siempre me pongo cansado después del trabajo.".into(),
                verb_aux: Some("sein".into()),
                trennbar: Some(false),
                reflexiv: Some(false),
            },
            New {
                gram_type: vec![4],
                gender_id: Some(1),
                worte_de: "Frist".into(),
                worte_es: "plazo (de entrega)".into(),
                plural: Some("Fristen".into()),
                niveau_id: 2,
                example_de: "Die Frist endet morgen.".into(),
                example_es: "El plazo termina mañana.".into(),
                verb_aux: None,
                trennbar: None,
                reflexiv: None,
            },
            New {
                gram_type: vec![15, 22],
                gender_id: None,
                worte_de: "rausgehen".into(),
                worte_es: "salir".into(),
                plural: None,
                niveau_id: 1,
                example_de: "Ich gehe kurz raus.".into(),
                example_es: "Salgo un momento.".into(),
                verb_aux: Some("sein".into()),
                trennbar: Some(true),
                reflexiv: Some(false),
            },
            New {
                gram_type: vec![2],
                gender_id: None,
                worte_de: "mehrere".into(),
                worte_es: "varios".into(),
                plural: None,
                niveau_id: 1,
                example_de: "Ich habe mehrere Möglichkeiten.".into(),
                example_es: "Tengo varias opciones.".into(),
                verb_aux: None,
                trennbar: None,
                reflexiv: None,
            },
            New {
                gram_type: vec![6],
                gender_id: None,
                worte_de: "wildfremd".into(),
                worte_es: "totalmente desconocido".into(),
                plural: None,
                niveau_id: 2,
                example_de: "Ein wildfremder Mann hat mir geholfen.".into(),
                example_es: "Un hombre totalmente desconocido me ayudó.".into(),
                verb_aux: None,
                trennbar: None,
                reflexiv: None,
            },
            New {
                gram_type: vec![19, 33],
                gender_id: None,
                worte_de: "bellen".into(),
                worte_es: "ladrar".into(),
                plural: None,
                niveau_id: 0,
                example_de: "Der Hund bellt laut.".into(),
                example_es: "El perro ladra fuerte.".into(),
                verb_aux: Some("haben".into()),
                trennbar: Some(false),
                reflexiv: Some(false),
            },
            New {
                gram_type: vec![7],
                gender_id: None,
                worte_de: "komm heile zurück".into(),
                worte_es: "regresa sano y salvo".into(),
                plural: None,
                niveau_id: 2,
                example_de: "Fahr vorsichtig und komm heile zurück.".into(),
                example_es: "Conduce con cuidado y regresa sano y salvo.".into(),
                verb_aux: None,
                trennbar: None,
                reflexiv: None,
            },
            New {
                gram_type: vec![11],
                gender_id: Some(1),
                worte_de: "Möglichkeit".into(),
                worte_es: "oportunidad".into(),
                plural: Some("Möglichkeiten".into()),
                niveau_id: 1,
                example_de: "Das ist eine gute Möglichkeit.".into(),
                example_es: "Esa es una buena oportunidad.".into(),
                verb_aux: None,
                trennbar: None,
                reflexiv: None,
            },
            New {
                gram_type: vec![18],
                gender_id: None,
                worte_de: "Schiss".into(),
                worte_es: "pánico".into(),
                plural: None,
                niveau_id: 2,
                example_de: "Ich habe keinen Schiss davor.".into(),
                example_es: "No tengo pánico de eso.".into(),
                verb_aux: None,
                trennbar: None,
                reflexiv: None,
            },
            New {
                gram_type: vec![14, 29],
                gender_id: None,
                worte_de: "sparen".into(),
                worte_es: "ahorrar".into(),
                plural: None,
                niveau_id: 1,
                example_de: "Ich spare Geld für meinen Urlaub.".into(),
                example_es: "Ahorro dinero para mis vacaciones.".into(),
                verb_aux: Some("haben".into()),
                trennbar: Some(false),
                reflexiv: Some(false),
            },
        ],
        update: vec![
            New {
                gram_type: vec![18, 40, 12],
                gender_id: Some(1),
                worte_de: "weitergehen test".into(),
                worte_es: "seguir test".into(),
                plural: Some("plural test".into()),
                niveau_id: 2,
                example_de: "Wir gehen weiter, bis wir zu Hause sind test.".into(),
                example_es: "Seguimos hasta llegar a casa test.".into(),
                verb_aux: Some("haben".into()),
                trennbar: Some(false),
                reflexiv: Some(true),
            },
            New {
                gram_type: vec![9, 31, 7],
                gender_id: None,
                worte_de: "müde werden, test".into(),
                worte_es: "ponerse cansado, test".into(),
                plural: Some("1234567890".into()),
                niveau_id: 5,
                example_de: "Ich werde nach der Arbeit immer müde.".into(),
                example_es: "Siempre me pongo cansado después del trabajo.".into(),
                verb_aux: None,
                trennbar: None,
                reflexiv: None,
            },
            New {
                gram_type: vec![4],
                gender_id: None,
                worte_de: "Frist test".into(),
                worte_es: "plazo (de entrega) test".into(),
                plural: None,
                niveau_id: 1,
                example_de: "tes tes test".into(),
                example_es: "1234567890".into(),
                verb_aux: Some("some".into()),
                trennbar: Some(true),
                reflexiv: Some(true),
            },
        ],
    }
}
